name: Build and run tests

on:
  push:
    branches:
      - main
    tags:
      - "!*" # not a tag push
    paths-ignore:
      - '**.md'
      - .github/**
      - docs/**
  pull_request:
    branches:
      - main
      - release/**
    paths-ignore:
      - '**.md'
      - .github/**
      - docs/**
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Run tests
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: Cysharp/Actions/.github/actions/checkout@main
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      - run: dotnet test -c Release

  publish-executables:
    name: Publish Executables
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    strategy:
      matrix:
        rid: [win-x64, win-arm64, linux-x64, linux-arm64]
    steps:
      - uses: Cysharp/Actions/.github/actions/checkout@main
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      - name: Publish Executable
        run:  dotnet publish src/AIApiTracer -r ${{ matrix.rid }} --self-contained -p:PublishSingleFile=true -o ./publish/${{ matrix.rid }}
      - name: Create ZIP file
        run: |
          cd ./publish/${{ matrix.rid }}
          zip -r ../AIApiTracer-${{ matrix.rid }}.zip .
      - uses: Cysharp/Actions/.github/actions/upload-artifact@main
        with:
          name: AIApiTracer-${{ matrix.rid }}
          path: ./publish/AIApiTracer-${{ matrix.rid }}.zip
          retention-days: 1

  publish-executables-macos:
    name: Publish Executables for macOS
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
    runs-on: macos-latest
    timeout-minutes: 10
    strategy:
      matrix:
        rid: [osx-arm64]
    steps:
      - uses: Cysharp/Actions/.github/actions/checkout@main
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      - name: Publish Executable
        run:  dotnet publish src/AIApiTracer -r ${{ matrix.rid }} --self-contained -p:PublishSingleFile=true -o ./publish/${{ matrix.rid }}
      - name: Create ZIP file
        run: |
          cd ./publish/${{ matrix.rid }}
          zip -r ../AIApiTracer-${{ matrix.rid }}.zip .
      - uses: Cysharp/Actions/.github/actions/upload-artifact@main
        with:
          name: AIApiTracer-${{ matrix.rid }}
          path: ./publish/AIApiTracer-${{ matrix.rid }}.zip
          retention-days: 1
